/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8crExS5dZVn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function Chatbot() {
  return (
    <div className="grid grid-cols-2 w-full h-screen">
      <div className="bg-background text-foreground p-6 overflow-auto">
        <div className="flex flex-col gap-4">
          <div className="flex items-start gap-4">
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="grid gap-1 bg-card p-3 rounded-lg max-w-[70%]">
              <div className="font-medium">You</div>
              <div className="text-card-foreground">Hey there! How can I help you today?</div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="grid gap-1 bg-primary p-3 rounded-lg max-w-[70%] text-primary-foreground">
              <div className="font-medium">AI Assistant</div>
              <div>Hello! I'm an AI assistant created by Vercel. How can I assist you today?</div>
            </div>
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AI</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-4">
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
            <div className="grid gap-1 bg-card p-3 rounded-lg max-w-[70%]">
              <div className="font-medium">You</div>
              <div className="text-card-foreground">
                I'm looking to create a new website for my business. Can you help me with that?
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="grid gap-1 bg-primary p-3 rounded-lg max-w-[70%] text-primary-foreground">
              <div className="font-medium">AI Assistant</div>
              <div>
                Absolutely! I'd be happy to assist you with creating a new website for your business. What kind of
                features or functionality are you looking for in the website?
              </div>
            </div>
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AI</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </div>
      <div className="bg-muted text-muted-foreground p-6 overflow-auto">
        <div className="flex flex-col gap-4">
          <div className="flex items-start gap-4">
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AI</AvatarFallback>
            </Avatar>
            <div className="grid gap-1 bg-card p-3 rounded-lg max-w-[70%]">
              <div className="font-medium">AI Assistant</div>
              <div className="text-card-foreground">
                Sure, I'd be happy to help you with that. What kind of website are you looking to create? Is it for a
                specific industry or type of business?
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="grid gap-1 bg-primary p-3 rounded-lg max-w-[70%] text-primary-foreground">
              <div className="font-medium">You</div>
              <div>
                I run a small e-commerce business selling handmade jewelry. I'd like a website that showcases my
                products, allows customers to easily browse and purchase items, and has a simple administrative backend
                for managing orders and inventory.
              </div>
            </div>
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </div>
          <div className="flex items-start gap-4">
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>AI</AvatarFallback>
            </Avatar>
            <div className="grid gap-1 bg-card p-3 rounded-lg max-w-[70%]">
              <div className="font-medium">AI Assistant</div>
              <div className="text-card-foreground">
                Okay, that sounds like a great plan. For an e-commerce website focused on showcasing and selling
                handmade jewelry, I would recommend the following key features:
                <ul className="list-disc pl-4 mt-2">
                  <li>
                    A clean, visually-appealing product catalog with high-quality images and detailed descriptions
                  </li>
                  <li>A shopping cart and secure checkout process to allow customers to purchase items</li>
                  <li>An admin dashboard to manage orders, inventory, and customer information</li>
                  <li>Search and filtering capabilities to help customers find products easily</li>
                  <li>Responsive design to ensure a great experience on both desktop and mobile</li>
                </ul>
                Does this sound like the kind of functionality you had in mind? I'd be happy to discuss further and
                provide more specific recommendations.
              </div>
            </div>
          </div>
          <div className="flex items-start gap-4 justify-end">
            <div className="grid gap-1 bg-primary p-3 rounded-lg max-w-[70%] text-primary-foreground">
              <div className="font-medium">You</div>
              <div>
                Yes, that sounds perfect! I really like the features you mentioned, especially the admin dashboard and
                responsive design. Can you provide some more details on how we could implement those capabilities?
              </div>
            </div>
            <Avatar className="w-10 h-10 border">
              <AvatarImage src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </div>
      <div className="col-span-2 bg-background border-t flex items-center px-6 py-4">
        <Textarea
          placeholder="Type your message..."
          className="flex-1 resize-none rounded-lg pr-16 bg-muted text-muted-foreground"
        />
        <Button type="submit" size="icon" className="ml-4 rounded-full" disabled>
          <SendIcon className="w-5 h-5" />
          <span className="sr-only">Send</span>
        </Button>
      </div>
    </div>
  )
}

function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
